# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55f9d0e2c9899752953f0db968f25cab18919deaaef34c6fa64f37205e2d6f4e6fea08ca40faf4ca3f42be42c0f49a3c71c4f41dbe90c213ea8fd8a4d18d9d38

test:
  secret_key_base: eec0f6333ab2bed4410621faf7860179b8e053afaaa907ac5d072a34970d31f8c9838585475ec6e933a5818709630197ed013199d95097c6f61b44229fde172d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
